In [220]:
from collections import Counter
import csv
from sklearn.metrics.pairwise import cosine_similarity

In [221]:
docs = [
    "Historia de Madrid: Madrid, la capital de España, tiene una rica historia que se remonta al siglo IX. La ciudad fue fundada por los musulmanes, y su nombre proviene del árabe “Majrit” que significa “fuente de agua”. A lo largo de los siglos, Madrid se ha convertido en un centro político, económico y cultural de España.",
    "El Palacio Real: El Palacio Real de Madrid es una de las residencias oficiales de la familia real española, aunque ahora se usa principalmente para ceremonias de estado. Con más de 3,000 habitaciones, es el palacio real más grande de Europa Occidental y un testimonio del esplendor y la historia de España.",
    "Museo del Prado: El Museo del Prado es uno de los museos más famosos del mundo y un destino imprescindible para los amantes del arte que visitan Madrid. Alberga una impresionante colección de obras de Velázquez, Goya, El Greco y otros maestros europeos.",
    "Parque del Retiro: El Parque del Retiro es el pulmón verde de Madrid. Antiguamente perteneciente a la monarquía española, este parque de 118 hectáreas ofrece un respiro de la vida urbana con sus estanques, jardines y el Palacio de Cristal.",
    "Gastronomía Madrileña: Madrid es famosa por su vibrante escena gastronómica que incluye desde tapas en pequeños bares hasta restaurantes de alta cocina. Platos típicos como el cocido madrileño y las patatas bravas son esenciales para cualquier visitante.",
    "Gran Vía: La Gran Vía es una de las calles más famosas de Madrid, conocida por sus tiendas, teatros y arquitectura emblemática. Este bullicioso bulevar es un punto de encuentro para turistas y locales por igual.",
    "Real Madrid y el Estadio Santiago Bernabéu: El Real Madrid, uno de los clubes de fútbol más famosos y exitosos del mundo, juega sus partidos en el Estadio Santiago Bernabéu. Este estadio es una meca para los aficionados al fútbol y ofrece tours que permiten a los visitantes explorar su rica historia.",
    "Navidad en Madrid: Durante la temporada navideña, Madrid se transforma con mercados festivos, luces deslumbrantes y decoraciones. La Plaza Mayor se convierte en un enorme mercado de Navidad, donde se pueden encontrar todo tipo de regalos y delicias tradicionales.",
    "Nochevieja en Puerta del Sol: La Puerta del Sol es el corazón de Madrid y el lugar donde miles se reúnen cada Nochevieja para dar la bienvenida al año nuevo. Comer las doce uvas de la suerte al son de las campanadas del reloj es una tradición que todos deberían experimentar.",
    "Madrid Río: Madrid Río es un parque lineal a lo largo del río Manzanares y un ejemplo perfecto de cómo la ciudad ha transformado áreas industriales en espacios verdes vibrantes. Es un lugar popular para caminar, andar en bicicleta y disfrutar de actividades al aire libre.",
    "Historia de Dortmund: Dortmund, situada en la región del Ruhr en Alemania, tiene una historia que se remonta al año 882. Originalmente una pequeña villa, Dortmund creció para convertirse en una importante ciudad industrial, especialmente conocida por su producción de acero y cerveza.",
    "Westfalenpark: Westfalenpark es uno de los parques urbanos más grandes de Europa y un lugar destacado para los visitantes en Dortmund. El parque es famoso por su Rosarium, que alberga una de las colecciones más extensas de rosas en el mundo, y la torre Florian, que ofrece vistas panorámicas de la ciudad.",
    "Museo del Fútbol Alemán: Inaugurado en 2015, el Museo del Fútbol Alemán ofrece una experiencia interactiva que celebra la rica historia del fútbol alemán. Ubicado en Dortmund, el museo atrae a aficionados de todo el mundo y destaca por sus exposiciones que cuentan desde los primeros días del deporte hasta los triunfos en Copas del Mundo.",
    "Mercado de Navidad de Dortmund: El Mercado de Navidad de Dortmund es uno de los más grandes y más visitados de Alemania. Con su gigantesco árbol de Navidad, posiblemente el más alto de los mercados navideños del país, y más de 300 puestos que venden artesanías, alimentos y bebidas tradicionales, es un evento imperdible durante la temporada festiva.",
    "U-Tower - Centro de Arte y Creatividad: El U-Tower, una antigua cervecería reconvertida, es ahora un centro dinámico de arte y creatividad. Alberga el Museo Ostwall, espacios de exposiciones y estudios de artistas, y es un símbolo de la transformación cultural de Dortmund.",
    "Borussia Dortmund y el Signal Iduna Park: Borussia Dortmund es uno de los clubes de fútbol más populares y exitosos de Alemania. El equipo juega sus partidos en casa en el Signal Iduna Park, conocido por su increíble atmósfera y el famoso “Muro Amarillo”, la tribuna sur que alberga a 25,000 aficionados apasionados.",
    "La cervecería Dortmund: Dortmund tiene una larga tradición cervecera, y la visita a una de sus muchas cervecerías es una parada obligatoria. Las cervecerías ofrecen tours que incluyen degustaciones de cervezas locales como Dortmunder Export, una lager que es un orgullo de la ciudad.",
    "La Reinoldikirche: La iglesia de San Reinold es el edificio más antiguo de Dortmund, datando del siglo XIII. Es un punto de referencia histórico importante y ofrece a los visitantes una mirada al pasado medieval de la ciudad.",
    "Dortmund durante la Segunda Guerra Mundial: Dortmund fue un objetivo significativo durante los bombardeos de la Segunda Guerra Mundial debido a su industria pesada. Hoy en día, varios monumentos y museos ofrecen reflexiones sobre este período y sus efectos en la ciudad.",
    "Zoológico de Dortmund: El Zoológico de Dortmund es un lugar excelente para familias y amantes de la naturaleza. Con más de 1,500 animales y un enfoque especial en la conservación de especies amenazadas, el zoológico proporciona una experiencia educativa y entretenida."
]

In [222]:
# all terms
# my diccionary
terms = set()
for document in docs:
    terms.update(document.lower().split())

In [223]:
matrix_frecuency = []
for document in docs:
    # count frecuency
    count = Counter(document.lower().split())
    #create frecuency
    frequency = [count.get(word, 0) for word in terms]
    #frecuency in matrix
    matrix_frecuency.append(frequency)

In [224]:
num_columns  = len(matrix_frecuency[0])
print (num_columns)

406


In [225]:
len(matrix_frecuency)

20

In [226]:
print(matrix_frecuency)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [227]:
for fila in matrix_frecuency:
    print(fila)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 

In [228]:
# create matrix frecuency
name_file = "matrix_frecuency.csv"

with open(name_file, "w", newline="") as archivo_csv:
    writer_csv = csv.writer(archivo_csv)
    writer_csv.writerow(terms)
    for fila in matrix_frecuency:
        writer_csv.writerow(fila)

In [229]:
print(f"Save CSV: '{name_file}'.")

Save CSV: 'matrix_frecuency.csv'.


In [230]:
#querys
query = [
    "Historia medieval de las ciudades europeas",
    "Principales destinos turisticos en Europa",
    "Influencia de la realeza en la cultura europea",
    "Importancia de los parques urbanos en las ciudades",
    "Gastronomia tipica en capitales europeas",
    "Eventos deportivos iconicos en Europa",
    "Celebraciones de Navidad en ciudades europeas",
    "Museos de arte importantes en Europa",
    "Efectos de la Segunda Guerra Mundial en ciudades europeas",
    "Arquitectura historica en ciudades europeas",
    "Clubes de futbol famosos y sus estadios en Europa",
    "Transformacion urbana y regeneracion de espacios",
    "Tradicion cervecera en ciudades europeas",
    "Mercados y comercio tradicional en Europa",
    "Centros de arte y creatividad en ciudades modernas",
    "Actividades de ocio y entretenimiento en ciudades metropolitanas",
    "Conservacion de la naturaleza y la vida silvestre en zonas urbanas",
    "Planificacion de eventos culturales y festivales en ciudades”",
    "Desarrollo del transporte y la infraestructura urbana",
    "Impacto de la tecnologia en la vida urbana"
]

In [231]:
len(query)

20

In [232]:
#matrix query
matrix_query = []

for document in query:
    # count frecuency
    count = Counter(document.lower().split())
    #create frecuency
    frequency = [count.get(word, 0) for word in terms]
    #frecuency in matrix
    matrix_query.append(frequency)

In [233]:
for fila in matrix_query:
    print(fila)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [234]:
distance = cosine_similarity(matrix_frecuency, matrix_query)

In [235]:
print(distance)

[[0.37310125 0.07537784 0.43519414 0.34815531 0.10660036 0.07537784
  0.36927447 0.28603878 0.32232919 0.07537784 0.32232919 0.37310125
  0.10660036 0.15990054 0.42640143 0.42640143 0.45226702 0.49236596
  0.2665009  0.37688918]
 [0.41079192 0.06454972 0.4099458  0.2981424  0.         0.06454972
  0.36893239 0.32659863 0.3105295  0.         0.34503278 0.41079192
  0.         0.13693064 0.41079192 0.41079192 0.4195732  0.47434165
  0.22821773 0.35502347]
 [0.18057878 0.         0.14744196 0.24573659 0.         0.
  0.20851441 0.26919095 0.13650473 0.         0.27300945 0.30096463
  0.         0.12038585 0.36115756 0.30096463 0.21281413 0.34752402
  0.36115756 0.12768848]
 [0.24253563 0.         0.39605902 0.19802951 0.         0.
  0.28005602 0.21693046 0.27500955 0.         0.27500955 0.36380344
  0.         0.06063391 0.30316953 0.30316953 0.42874646 0.35007002
  0.36380344 0.42874646]
 [0.16439899 0.11624764 0.13423121 0.20134682 0.16439899 0.11624764
  0.1898316  0.14704292 0.124273

In [236]:
len(distance)

20

In [237]:
import numpy as np

top_3 = []
for fila in distance:
  index = np.argsort(fila)[-3:][::-1]
  top_3.append(fila[index])

In [238]:
print(top_3)

[array([0.49236596, 0.45226702, 0.43519414]), array([0.47434165, 0.4195732 , 0.41079192]), array([0.36115756, 0.36115756, 0.34752402]), array([0.42874646, 0.42874646, 0.39605902]), array([0.2847474 , 0.24659848, 0.24659848]), array([0.40824829, 0.35355339, 0.35355339]), array([0.37796447, 0.37115374, 0.32732684]), array([0.48564293, 0.47583095, 0.44861772]), array([0.45360921, 0.43212081, 0.3928371 ]), array([0.4375   , 0.4330127, 0.375    ]), array([0.45098762, 0.39056673, 0.39056673]), array([0.55391171, 0.52223297, 0.48995593]), array([0.34320324, 0.2941742 , 0.2941742 ]), array([0.55117825, 0.50524673, 0.47733437]), array([0.61558701, 0.59234888, 0.56428809]), array([0.49518757, 0.42884501, 0.42884501]), array([0.4271211 , 0.41099747, 0.36989772]), array([0.53605627, 0.51066218, 0.46423835]), array([0.58554004, 0.50207901, 0.47434165]), array([0.58461282, 0.51711223, 0.50628956])]


In [239]:
len(top_3)

20

In [240]:
query_matrix = np.array(query)
top_3_matrix = np.array(top_3)

In [241]:
concatenated_matrix = np.empty((len(query_matrix), 2), dtype=object)

In [242]:
for i in range(len(query_matrix)):
    concatenated_matrix[i] = [query_matrix[i], top_3_matrix[i]]

In [243]:
print(concatenated_matrix)

[['Historia medieval de las ciudades europeas'
  array([0.49236596, 0.45226702, 0.43519414])]
 ['Principales destinos turisticos en Europa'
  array([0.47434165, 0.4195732 , 0.41079192])]
 ['Influencia de la realeza en la cultura europea'
  array([0.36115756, 0.36115756, 0.34752402])]
 ['Importancia de los parques urbanos en las ciudades'
  array([0.42874646, 0.42874646, 0.39605902])]
 ['Gastronomia tipica en capitales europeas'
  array([0.2847474 , 0.24659848, 0.24659848])]
 ['Eventos deportivos iconicos en Europa'
  array([0.40824829, 0.35355339, 0.35355339])]
 ['Celebraciones de Navidad en ciudades europeas'
  array([0.37796447, 0.37115374, 0.32732684])]
 ['Museos de arte importantes en Europa'
  array([0.48564293, 0.47583095, 0.44861772])]
 ['Efectos de la Segunda Guerra Mundial en ciudades europeas'
  array([0.45360921, 0.43212081, 0.3928371 ])]
 ['Arquitectura historica en ciudades europeas'
  array([0.4375   , 0.4330127, 0.375    ])]
 ['Clubes de futbol famosos y sus estadios en 

In [244]:
# create matrix 
name_file = "matrix_query_and_top3.csv"

# write in csv
with open(name_file, "w", newline="", encoding="utf-8") as archivo_csv:
    writer_csv = csv.writer(archivo_csv)
    for fila in concatenated_matrix:
        writer_csv.writerow(fila)